version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - REPO_URI=$APP_ECR_URI
      - IMAGE_TAG=rev-$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Logging in to Docker
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest -t $REPO_URI:$IMAGE_TAG ./app
      - echo Build completed on `date`
      - echo Logging out of Docker
      - docker logout
  post_build:
    commands:
      - echo Pushing the image...
      - docker push $REPO_URI:$IMAGE_TAG
