version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - REPO_URI=$BACKEND_REPO_URI
      - IMAGE_TAG=rev-$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Logging in to Docker
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest -t $REPO_URI:$IMAGE_TAG ./app
      - echo Build completed on `date`
      - echo Logging out of Docker
      - docker logout
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pushing the Docker images...
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"backendContainer","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > backend.json
      - printf '[{"name":"queueWorkerContainer","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > queueWorker.json
artifacts:
  files:
    - backend.json
    - queueWorker.json